### ISSUE TITLE
Punctuation Settings not getting applied

### ISSUE THREAD

**Issue by kausha** [md-systems/pathauto#98] opened 2015-12-11 09:55 UTC
The punctuation settings are not getting applied in the url alias generation. Currently all the punctuation mark as set to "Remove" but it is not removing the marks instead it is replacing it by separator being set [- in my case]. I want to remove all these punctuation mark from the url alias structure. Also, changing the settings from other than "Remove" is not allowing to save the setting. 

Please help me up for this.

**Comment by Berdir** [comment] 2015-12-11 10:05
Thanks for reporting, I think this is a duplicate of https://github.com/md-systems/pathauto/pull/86.

**Comment by kausha** [comment] 2015-12-11 11:47
Not similar to the issue I am facing. Punctuation mark should get stripped off instead of getting replaced by separator. Seems form is not saving the setting of punctuation

**Comment by kausha** [comment] 2015-12-14 06:02
Any update for this?

**Comment by Berdir** [comment] 2016-01-01 10:30
> Seems form is not saving the setting of punctuation

Yes, that's exactly what the other issue was about. And it should be fixed now.

**Closed as completed by Berdir** 2016-01-01 10:30 UTC
