### ISSUE TITLE
Language specific patterns not being applied

### ISSUE THREAD

**Issue by idflood** [md-systems/pathauto#92] opened 2015-11-11 09:32 UTC
For instance the pattern defined for "all French Basic page path" are never applied. To reproduce:
1. Enable multiple languages
2. Make the page content type translatable
3. Define different path patterns for this content type.

Then only the "default pattern" is applied and never the language specific one.

**Comment by idflood** [comment] 2015-11-11 09:45
The issue may be in `PathautoManager->getPatternByEntity()`. This function tries to get the config from:

```
$variables[] = "{$entity_type_id}.bundles.{$bundle}.languages.{$language}";
```

But in fact the config I get looks like this (without the .languages and instead `{$bundle}_{$language}`):

```
patterns:
  node:
    default: '/content/[node:title]'
    bundles:
      article:
        default: ''
      page:
        default: ''
      page_fr:
        default: '/page-fr/[node:title]'
      page_de:
        default: '/page-de/[node:title]'
      page_en:
        default: '/page-en/[node:title]'
```

edit:
One other issue is that this function do this:

```
if ($pattern = trim($config->get('patterns.' . $variable)))
```

But in fact `$config->get('patterns.' . $variable)` doesn't return a string but an array with a ['default'] if there is a result.

**Comment by Berdir** [comment] 2015-11-11 10:19
This might again be a form problem, the way it checks for language is correct.

Note that we're working on completely refactoring the way patterns are managed and stored in https://github.com/md-systems/pathauto/tree/pattern-config-entities. So not going to spend time on fixing the current form, hopefully the other issue will get committed pretty soon.

**Comment by juampynr** [comment] 2015-12-29 09:43
There is another branch where even more recent work has been made: https://github.com/md-systems/pathauto/tree/pattern-config-entities-simplified-ui

I will test the above issue at this branch.

**Comment by Berdir** [comment] 2016-01-01 10:31
Closing this as a duplicate of the merged config entity refactoring. Pretty sure that we'll find more issues there, but this problem should be fixed. We even included an upgrade path for the wrong settings.

**Closed as completed by Berdir** 2016-01-01 10:31 UTC
