### ISSUE TITLE
Path pattern not updating properly

### ISSUE THREAD

**Issue by CarlosGatlin** [md-systems/pathauto#76] opened 2015-09-24 21:43 UTC
Using the default path pattern for content we placed:
/[node:menu-link:parents:join-path]/[node:title]
But the node has to be saved twice for it to take the proper path pattern.

example creating a page under the menu home will result in the path /page when it should be /home/page.
Saving the page a second time will give it the the proper path /home/page

using drupal 8 beta15 with standard profile
and commit d4422eb of pathauto.

Update: still happens on rc1 with commit e850af1

**Comment by sebastianwestberg** [comment] 2015-10-14 10:55
+1. Same thing here on beta15 and rc1.

**Comment by Berdir** [comment] 2015-10-20 18:29
I fear that's not going to work anymore, nothing this module or token can do something about.

The menu links are saved/pdated _after_ the node has been saved, not before/at the same time. And the information for it is not available on the node object because it is not a field. You will have to find a different way to build your aliases for now.

**Comment by idflood** [comment] 2015-10-21 10:16
Sad to hear this is probably not possible in drupal 8. The token in itself works so I believe this is more an issue with pathauto.

Is there any chance to find a workaround? The menu links is not available as a field on node save but I think that the information about the parent menu item and menu link title is available somewhere (in the form state maybe).

edit: throwing an idea... maybe there is something to do on the MenuLinkContent entity update/insert

**Comment by Berdir** [comment] 2015-10-26 07:32
It's not a Pathauto problem. Pathauto just does a token replace call, tokens are not provided by us (with very few exceptions).

**Comment by idflood** [comment] 2015-10-26 08:06
So maybe we should create a new tiny workaround module? I understand that in fact it's not a bug in pathauto and neither in token module (even core is not the culprit I think).

I'm searching a solution since this token works when a node is saved a second time and I think it's one of the most useful to have a clean hierarchical url. The workaround I'm imagining would look like this:

```
// For hook_entity_insert and maybe hook_entity_update
global $pathauto_save_next_menu_link;
if ($entity->getEntityTypeId() === 'node') {
  $pathauto_save_next_menu_link = TRUE;
}
if ($entity->getEntityTypeId() === 'menu_link_content' && $pathauto_save_next_menu_link) {
  $target_entity = something_to_load_an_entity_by_uri($entity->link->first()->uri);
  \Drupal::service('pathauto.manager')->updateAlias($target_entity, 'update');
  $pathauto_save_next_menu_link = FALSE;
}
```

**Comment by Berdir** [comment] 2015-10-26 08:10
Well, core kind of is because the behavior of how that information is submitted/processed/saved changed completely. in 7.x, we just put the whole form values onto the node object and token.module had two implementations for that token, one that pulled it of there and one that pulled it of in the storage.

This is gone because menu links are now stored through the form system and not entity hooks. And we can't access that since we still work with entity hooks (correctly so, IMHO). the only place where it would be available the global POST variables, but that's obviously not really a solution.

**Comment by idflood** [comment] 2015-11-02 15:46
For information here is a super hacky solution. The following needs to be added to hook_entity_insert and hook_entity_update:

```
// For hook_entity_insert and maybe hook_entity_update
global $pathauto_save_next_menu_link;
if ($entity->getEntityTypeId() === 'node') {
  $pathauto_save_next_menu_link = TRUE;
}
if ($entity->getEntityTypeId() === 'menu_link_content' && $pathauto_save_next_menu_link) {
  // Rebuild the menu links.
  $menu_link_manager = \Drupal::service('plugin.manager.menu.link');
  $menu_link_manager->rebuild();

  $uri = $entity->link->first()->uri;
  $nid = intval(str_replace('entity:node/', '', $uri));
  $storage = \Drupal::entityManager()->getStorage('node');

  // Reset some caches.
  $storage->resetCache(array($nid));
  // Clear the cache used in token_menu_link_load_all_parents().
  $pluginId = $entity->getPluginId();
  // drupal_static_reset($pluginId);
  // Another cache make the above function not working so we clear all caches.
  drupal_static_reset();
  $node = \Drupal\node\Entity\Node::load($nid);

  \Drupal::entityManager()->getStorage('menu_link_content')->resetCache();
  \Drupal::service('pathauto.manager')->updateAlias($node, 'update', array('force' => TRUE));
  $pathauto_save_next_menu_link = FALSE;
}
```

**Comment by ceesgeene** [comment] 2015-11-05 00:31
This seems to work:

``` php
  global $pathauto_resave_node;

  $entity_type = $entity->getEntityTypeId();
  if ($entity_type === 'node') {
    $pathauto_resave_node = $entity;
  }
  elseif ($entity_type === 'menu_link_content' && $pathauto_resave_node) {
    // Clear the cache used in token_menu_link_load_all_parents().
    drupal_static_reset('token_menu_link_load_all_parents');

    \Drupal::service('pathauto.manager')->updateAlias($pathauto_resave_node, 'update', array('force' => TRUE));
    $pathauto_resave_node = FALSE;
  }
```

**Comment by idflood** [comment] 2015-11-05 10:44
Thanks @ceesgeene this works perfectly. I've created a github repo with a module implementing this solution https://github.com/idflood/pathauto_menu_link_parents_hack

**Comment by Berdir** [comment] 2015-11-05 10:49
That's a scary thing to do ;)

An alternative, generic approach might be to do the alias generation at the end of the request, through an onTerminate event or maybe by using the needs_destruction service tag (has the advantage of only being called if it was instantiated). Then it would always be after all the things were saved.

The problem is that it actually happens after sending the response to the user. It could result in the alias not being saved yet by the time the user access the page again and he'd see a non-aliased page.

**Comment by idflood** [comment] 2015-11-06 06:44
@Berdir should we create an issue on do to add a new `hook_entity_after_save` to core or something like that? If pathauto could use this instead of the 2 update and insert hooks maybe this issue could be fixed in 8.1.

**Comment by Berdir** [comment] 2015-11-06 09:04
hook_entity_insert() is already after, there is no way to execute a hook later on. Saving the menu link happens completely separated from saving the node.

**Comment by akalata** [comment] 2016-01-04 20:02
`[node:menu-link:parents:join-path]` is no longer a valid token  (using the latest dev version 2016-Jan-03).

`[node:menu-link:parents:join:/]`works when the node has fewer than 2 menu parents. Which I guess is the same as saying only one parent exists, so the `join` isn't working? Seems like a token issue in any case.

**Comment by tormu** [comment] 2016-01-05 14:47
It's a bit off topic on this one, but as a reply to akalata:
My path pattern is  /[node:menu-link:parents:join-path]/[node:menu-link:title] and it seems to be working ok - I mean that it doesn't say it's not a valid one. Tried with one parent and two parents, they both work.

Using dev 2016-Jan-03 for token and latest (like 2 hours ago) snapshot of https://github.com/md-systems/pathauto/tree/8.x-1.x

**Comment by akalata** [comment] 2016-01-05 16:00
Thanks @tormu! I had downloaded the zip for 8.x-1.x (files timestamped Jan 1). Grabbing a fresh version using git clone, and everything works great. 

Sorry for the noise in this thread. :)

**Comment by roberttom** [comment] 2016-01-20 09:27
So pathauto reacts on entity_save, menu_ui adds a a form submit handler which runs after the whole entity save process. Can't pathauto add a form_submit handler to the node_form after the menu_ui handler to take care of this situation?

Maybe it's not so bad to react on a menu_link(_content) save for [node:menu-link:parents:join-path]. What should happen if a menu item is re-positioned the menu system. Should the alias be updated?

**Comment by Berdir** [comment] 2016-01-24 19:39
Pathauto moved back to drupal.org. Please open a new issue there to continue this discussion.

**Closed as completed by Berdir** 2016-01-24 19:39 UTC
